services:
  chainlit-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./sqlite:/app/sqlite
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    env_file:
      - .env
